apiVersion: apps/v1
kind: ReplicaSet      
metadata:
  name: kubia                     
spec:
  replicas: 4                 
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [kubia, kubia1]}                  
  template:                        
    metadata:                      
      labels:                      
        app: kubia                 
    spec:                          
      containers:                  
      - name: kubia                
        image: luksa/kubia         
        ports:                     
        - containerPort: 8080                          
