ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "Master" do |kmaster|
    kmaster.vm.box = "centos/7"
    kmaster.vm.hostname = "Master"
    kmaster.vm.network "private_network", ip: "192.168.56.130"
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "Master"
      v.memory = 3048
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
    kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh"
  end

  NodeCount = 5

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "Worker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "Worker#{i}"
      workernode.vm.network "private_network", ip: "192.168.56.13#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "Worker#{i}"
        v.memory = 1536
        v.cpus = 1
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end
 end